name: Whatever
on:
  push:
    branches:
      - master

jobs:
  builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - matrix: # this is a configuration object that is transformed to...
            - go: 1.13
              commit: v1.0.0
              effort: 1
            - go: 1.14
              commit: v1.2.0
              effort: 2
            - go: 1.15
              commit: v1.6.0
            tensor: # this is a configuration object that is transformed to...
            - go: 2.13
              commit: v2.0.0
            - go: 2.14
              commit: v2.2.0
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result1 }}
      tensor: ${{ steps.set-matrix.outputs.result2 }}
    steps:
      - id: set-matrix
        run: |
          export effort=2
          echo '${{ toJSON(matrix.matrix) }}' | jq -r 'map(select(.effort <= env.effort)) | "::set-output name=result1::\(.)"'
          echo '${{ toJSON(matrix.tensor) }}' | jq -r '"::set-output name=result2::\(.)"'

  runner:
    needs: [ builder ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ${{ fromJson(needs.builder.outputs.matrix) }}
    steps:
      - name: dump
        run: |
          echo "${{ matrix.server.go }} ${{ matrix.server.commit }}"
