name: Whatever
on:
  push:
    branches:
      - master

jobs:
  matrix:
    name: Define matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(matrix.include) }}
    strategy:
      matrix:
        include:
          - name: hello
          - name: world
    steps:
    - run: ${{ toJSON(matrix) }}

  use_matrix:
    name: Use matrix
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        include: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
    - name: dump
      run: echo " ${{ matrix.name }}"
