name: Whatever
on:
  push:
    branches:
      - master

jobs:
  matrix:
    name: Define matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(matrix) }}
    strategy:
      matrix:
        cfog:
          - data:
            - { go: 1.13, commit: v1.0.0 }
            - { go: 1.14, commit: v1.2.0 }
    steps:
    - run: echo "${{ toJSON(matrix.cfog) }}"

  use_matrix:
    name: Use matrix
    runs-on: ubuntu-latest
    needs: matrix
    #strategy:
    #  matrix:
    #    include: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
    - name: dump
      run: echo " ${{ needs.matrix.outputs.matrix }}"
