name: Whatever
on:
  push:
    branches:
      - main

jobs:
  matrix:
    name: Define matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(matrix) }}
    matrix:
      hello: [1, 2, 3]
      include:
      - name: world
    steps:
    - run: echo "noop"
  use_matrix:
    name: Use matrix
    needs: matrix
    matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
    - name: dump
      run: echo "${{ matrix.hello }} ${{ matrix.name }}"
