name: Whatever
on:
  push:
    branches:
      - master

jobs:
  matrix:
    name: Define matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(matrix) }}
    strategy:
      matrix:
        hello: [1, 2, 3]
        include:
          - name: world
    steps:
    - run: echo "noop"

  use_matrix:
    name: Use matrix
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
    - name: dump
      run: echo "${{ matrix.hello }} ${{ matrix.name }}"
