name: Whatever
on:
  push:
    branches:
      - master

jobs:
  matrix:
    name: Define matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.process.outputs.matrix }}
    strategy:
      matrix:
        matrix:
          - matrix:
            - { go: 1.13, commit: v1.0.0 }
            - { go: 1.14, commit: v1.2.0 }
    steps:
    - id: process
      env:
        matrix: ${{ toJSON(matrix.matrix) }}
      run: jq -r -n 'env.matrix | fromjson | @json "::set-output name=result::\(.matrix)"'

  use_matrix:
    name: Use matrix
    runs-on: ubuntu-latest
    needs: matrix
    strategy:
      matrix:
        matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
    - name: dump
      run: echo "${{ matrix.matrix.go }} ${{ matrix.matrix.commit }}"
