name: Whatever
on:
  push:
    branches:
      - master

jobs:
  matrix:
    name: Define matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ toJSON(matrix) }}
    strategy:
      matrix:
        solo:
          config:
          - name: hello
          - name: world
    steps:
    - run: echo "${{ toJSON(matrix) }}"

  use_matrix:
    name: Use matrix
    runs-on: ubuntu-latest
    needs: matrix
    #strategy:
    #  matrix:
    #    include: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
    - name: dump
      run: echo " ${{ needs.matrix.outputs.matrix }}"
