name: Whatever
on:
  push:
    branches:
      - master

jobs:
  builder:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - matrix:
            - go: 1.13
              commit: v1.0.0
            - go: 1.14
              commit: v1.2.0
    outputs:
      matrix: ${{ steps.set-matrix.outputs.result }}
    steps:
      - id: set-matrix
        run: echo '${{ toJSON(matrix.matrix) }}' | jq -r '"::set-output name=result::\(.matrix)"'

  runner:
    needs: [ builder ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ${{ fromJson(needs.builder.outputs.matrix) }}
    steps:
      - name: dump
        run: |
          echo "${{ matrix.server.go }} ${{ matrix.server.commit }}"
